/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 donut.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/donut.glb')
  return (
    <group {...props} dispose={null} scale={[2.5, 2.5, 2.5]}>
      <mesh geometry={nodes.Icing.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes.Donut.geometry} material={materials['Material.002']} />
    </group>
  )
}

useGLTF.preload('/donut.glb')
