/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 monkey.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/monkey.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Suzanne.geometry} material={materials['Material.001']} rotation={[0, -0.961, 0]} />
      <mesh geometry={nodes.Cone.geometry} material={materials['Material.002']} position={[0, 1.677, 0]} scale={[0.716, 0.845, 0.716]} />
    </group>
  )
}

useGLTF.preload('/monkey.glb')
