/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 shoe.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/shoe.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-0.041, 0, 0]}>
        <mesh geometry={nodes.Textured_mesh_1_1.geometry} material={materials.Textured_mesh_1_tex0} />
        <mesh geometry={nodes.Textured_mesh_1_2.geometry} material={materials.Textured_mesh_1_tex1} />
      </group>
    </group>
  )
}

useGLTF.preload('/shoe.glb')
