/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 shoe-test.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/shoe-test.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ASSET.geometry} material={materials.PTRCWLNCNKKGAJZX_MAT_MR} />
    </group>
  )
}

useGLTF.preload('/shoe-test.glb')
